### ISSUE TITLE
Add pre-commit configs

### ISSUE THREAD

**Issue by Goldziher** [dosisod/refurb#10]
hiya,

I'd be happy to test your tool - if you can add pre-commit configs. We rely heavily on this tool, also in CI. See: https://github.com/starlite-api/starlite/blob/main/.pre-commit-config.yaml

Cheers

**Comment by dosisod** [comment]
Thank you for showing such interest in Refurb! I've heard about `pre-commit`, but never used it before, so I will have to my research first. I don't expect this to be terribly hard to do.

**Comment by Goldziher** [comment]
> Thank you for showing such interest in Refurb! I've heard about `pre-commit`, but never used it before, so I will have to my research first. I don't expect this to be terribly hard to do.

sure thing. Yes, its not hard to do at all - you simply add a yaml file to your repository called `.pre-commit-hooks.yaml` with settings. See: https://pre-commit.com/#new-hooks for more details. You're welcome to clone Starlite and add your hook to the `.pre-commit-config.yaml` in our repository and try it out, you'll also see what kind of issues your tool picks up in our fairly complex and very linted codebase.

**Comment by EFord36** [comment]
Hi,

I also just came across refurb today, and thought it looked really interested, but would be really useful to have easily available to use with pre-commit. I opened #19 to address this - hope you don't mind and that it's useful for you! No problem if you can't get to it immediately or if you want to take some time to get familiar with pre-commit before considering the PR.

Thanks for refurb!

**Comment by dosisod** [comment]
Closed via #19 

Thank you @Goldziher for reporting this, and @EFord36 for implementing it!

**Comment by Goldziher** [comment]
Actually, the config doesn't work:

I add this to the configs:
```yaml
  - repo: https://github.com/dosisod/refurb
    rev: ""
    hooks:
      - id: refurb
```

Then ran `pre-commit autoupdate`

And i get this:

```shell
Updating https://github.com/dosisod/refurb ... [INFO] Initializing environment for https://github.com/dosisod/refurb.

=====> /Users/naamanhirschfeld/.cache/pre-commit/repo37wx0r4m/.pre-commit-hooks.yaml is not a file
```

Also -- after its working, I suggest adding a section in the readme about this. 

@EFord36 @dosisod

**Comment by dosisod** [comment]
Since I have not tagged a release yet, you will have to do `pre-commit autoupdate --bleeding-edge` to pull from the latest commit instead of the latest tag. Also, you could just use `rev: "66e6874c"` to pin it at the most recent commit, but I don't think you would be able to auto update once a tag is released (I might be wrong on that).

I have a lot of things to add to the README, and I will make sure to mention this when I update it tomorrow.
