### ISSUE TITLE
[Bug]: Misleading mypy error for duplicate modules

### ISSUE THREAD

**Issue by The-Compiler** [dosisod/refurb#101]
### The Bug

With a reproducer such as:

```shell
$ mkdir -p repro/sub
$ touch repro/mod.py
$ touch repro/sub/mod.py
$ tree repro
repro
├── mod.py
└── sub
    └── mod.py
```

running `refurb repro` results in:

```
repro/mod.py: error: Duplicate module named "mod" (also at "repro/sub/mod.py")
repro/mod.py: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#mapping-file-paths-to-modules for more info
repro/mod.py: note: Common resolutions include: a) using `--exclude` to avoid checking one of them, b) adding `__init__.py` somewhere, c) using `--explicit-package-bases` or adjusting MYPYPATH
```

which seems to be a mypy-internal error message: None of the suggested resolutions (except the `__init__.py` one) make any sense in the context of `refurb`, and the suggested arguments do not exist.

### Version Info

```shell
Refurb: v1.5.0
Mypy: v0.982
```

### Python Version

Python 3.10.8

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Thank you for reporting this! I don't know what the best way of going about fixing this is, the methods described in that link didn't seem to help. I will keep searching though!

I've also been playing with the idea of being able to pass in flags to mypy directly, such as:

```
refurb repro -- --exclude repro/mod.py
```

This would "solve" the problem, but would mean that `repro/mod.py` would not be checked anymore.
