### ISSUE TITLE
[Bug]: FURB110 problem with class attributes

### ISSUE THREAD

**Issue by bbkgh** [dosisod/refurb#112]
### The Bug

The following code:

```python
class aClass:
    bAttr = 4
    cAttr = 5


_ = aClass.bAttr if aClass.cAttr else 5

```

Emits the following error:

```
$ refurb file.py
(test.py:6:5 [FURB110]: Replace `x if x else y` with `x or y`)
```

But it should not be emitting an error instance because...

### Version Info

```shell
Refurb: v1.6.0
Mypy: v0.981
```

### Python Version

Python 3.11.0

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Thank you for reporting this! I should've caught this one
