### ISSUE TITLE
[Bug]: FURB124 problem with class attributes

### ISSUE THREAD

**Issue by bbkgh** [dosisod/refurb#113]
### The Bug

The following code:

```python
class aClass:
    bAttr = 4
    cAttr = 5

aClass.bAttr == 1 and aClass.cAttr == 2
```

Emits the following error:

```
$ refurb file.py
test.py:5:1 [FURB124]: Replace `x == y and x == z` with `x == y == z`
```

But it should not be emitting an error instance because...

### Version Info

```shell
Refurb: v1.6.0
Mypy: v0.981
```

### Python Version

Python 3.11.0

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Closed via #115
