### ISSUE TITLE
[Bug]: FURB108 problem with class attributes

### ISSUE THREAD

**Issue by jpmx** [dosisod/refurb#114]
### The Bug

The following code:

```python
class MyClass:
    a_attr = 0
    b_attr = 0


if MyClass.a_attr == 0 or MyClass.b_attr == 0:
    pass
```

Emits the following error:

```
$ refurb file.py
file.py:6:4 [FURB108]: Replace `x == y or x == z` with `x in (y, z)`
```

But it should not be emitting an error instance because...

### Version Info

```shell
Refurb: v1.6.0
Mypy: v0.981
```

### Python Version

Python 3.11.0

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Closed via #112
