### ISSUE TITLE
[Bug]: FURB108 issues

### ISSUE THREAD

**Issue by shaolo1** [dosisod/refurb#117]
### The Bug

The following code:

```python
d1 = 2
d2 = 3
foo = '1' if (d1 == 1 or d2 == 1) else '2'  # Not flagged


class Foo:
    d = 1
    d1 = 2
    d2 = 3


f = Foo()
foo = '1' if (f.d1 == 1 or f.d2 == 1) else '2'

```

Emits the following error:

```
$ refurb refurb2.py
refurb2.py:13:15 [FURB108]: Replace `x == y or x == z` with `x in (y, z)`

Run `refurb --explain ERR` to further explain an error. Use `--quiet` to silence this message

```

But it should not be emitting an error instance because...

It should flag both cases, not just the class one.  Also the error message should be different in this case since to make it valid the check needs rewriting as 1 in (f.d1, f.d2)

### Version Info

```shell
Refurb: v1.6.0
Mypy: v0.990
```

### Python Version

Python 3.11.0

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Closed for the same reason as #116

**Comment by shaolo1** [comment]
Did you catch the bit about the error message needing some sharpening in this case since the code needs a bit of a rewrite?

**Comment by dosisod** [comment]
Sorry, I read this one a bit too fast! You're right, this check should be able to catch the `(d1 == 1 or d2 == 1)`, which also means the error message will need to be tweaked.
