### ISSUE TITLE
[Bug]: FURB110 issures

### ISSUE THREAD

**Issue by shaolo1** [dosisod/refurb#119]
### The Bug

The following code:

```python
foo = 1
bar = 2
baz = 3
bam = foo if bar else baz  # Not flagged


class Foo:
    foo = 1
    bar = 2
    baz = 3


f = Foo()
bam = f.foo if f.bar else f.baz


```

Emits the following error:

```
$ refurb refurb3.py
refurb3.py:16:7 [FURB110]: Replace `x if x else y` with `x or y`

Run `refurb --explain ERR` to further explain an error. Use `--quiet` to silence this message

```

But it should not be emitting an error instance because...

I'm guessing it is expecting bam = f.bar if f.bar else f.baz ...that would make sense, but not the case here.  Also only flagged in class case.

### Version Info

```shell
Refurb: v1.6.0
Mypy: v0.990
```

### Python Version

Python 3.11.0

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Closing this for the same reason as #116. As you have probably seen, there is a helper function which isn't checking that the names of the member expressions (ie, `x.y` and `x.z`) are the same, and as such, it incorrectly says that the expressions are the same.
