### ISSUE TITLE
Be able to define location of pyproject.toml file

### ISSUE THREAD

**Issue by nth10sd** [dosisod/refurb#15]
https://github.com/dosisod/refurb/blob/8e016048966022023cf8b165f93b8f26e3bef1e7/refurb/settings.py#L133

`pyproject.toml` seems hard-coded to be in the same folder as `refurb`. Can we add a new settings option to define the location of `pyproject.toml`?

**Comment by dosisod** [comment]
Yes, having a `--config-file` option or something similar would be a good idea!

**Comment by dosisod** [comment]
Closed via #62
