### ISSUE TITLE
[Bug]: Wrong FURB145 for numpy arrays

### ISSUE THREAD

**Issue by jonathanberthias** [dosisod/refurb#155]
### Has your issue already been fixed?

- [X] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

The following code:

```python
import numpy as np

np.array([[1, 2, 3]])[:,0]
```

Emits the following error:

```
$ refurb file.py
furb.py:-1:0 [FURB145]: Replace `x[:]` with `x.copy()`
```

There are 2 issues:
1. Arrays with multiple dimensions can have one dimension indexed with `:`, but that is not the same as copying the entire array;
2. The line number in the error message is `-1`.

### Version Info

```shell
Refurb: v1.8.0
Mypy: v0.991

(installed from git)
```

### Python Version

Python 3.10.6

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Very interesting! Thank you for reporting this, I will take a look at it later tonight!
