### ISSUE TITLE
[Bug]: Improve suggestion for dict({...})

### ISSUE THREAD

**Issue by eendebakpt** [dosisod/refurb#187]
### Has your issue already been fixed?

- [X] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

The following code:

```python
dict({'xmlns': 'http://www.w3.org/1999/xhtml', 'xml:lang': 'en'})
```

Emits the following message:

```
$ refurb file.py
file.py:2:1 [FURB123]: Replace `dict(x)` with `x.copy()`
```

A correct suggestion would be to just drop the `dict()`, e.g.
```
file.py:2:1 [FURB123]: Replace `dict({x})` with `{x}`
```

### Version Info

```shell
Refurb: v1.10.0
Mypy: v0.990
```

### Python Version

3.10.9

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Thank you for reporting this @eendebakpt!
