### ISSUE TITLE
Integrate with ruff

### ISSUE THREAD

**Issue by justinchuby** [dosisod/refurb#190]
I enjoyed using refurb to keep my code clean and fresh. Naively I think it would be awesome to integrate refurb's rules to https://github.com/charliermarsh/ruff to take advantage of its fast speed.

**Comment by dosisod** [comment]
I haven't played around with Ruff yet, but from what I can see it looks promising. The issue with integrating Refurb and Ruff together is that it would require re-writing Refurb in Rust, and then updating both Refurb and the upstream Ruff whenever a check or update is added. With that in mind, it would make more sense that Refurb be merged into Ruff, meaning the `refurb` package would cease to exist. An alternative would be to use/fork Ruff and only implement the checks that Refurb cares about, that way Refurb can still be a standalone application, but benefit from the speed of Ruff.

All in all, this is going to be a lot of work. I will (eventually) look into this more to see if it is feasible, but for the time being I feel as though Refurb should be left as it is. I am open to others investigating or implementing this, but I myself will not be working on it.

Thank you for opening this issue though! Refurb is slow, and I am looking at ways to make it faster. Ruff might be the answer, though it will take some investigation to say for sure.

**Comment by sbrugman** [comment]
Note that we started by porting a couple of [`pathlib` rules](https://github.com/charliermarsh/ruff/pull/2348) from refurb! (They are categorized under [`flake8-use-pathlib`](https://gitlab.com/RoPP/flake8-use-pathlib) for conciseness, but should receive FURBXXX alias codes)

**Comment by dosisod** [comment]
This is really cool! I am glad to see these sorts of checks get adopted by other tools. Another feature of Ruff I didn't see before is the autofixing capabilities, which is another thing I eventually want to implement in Refurb at some point.

And I will make sure to look at Ruff so I can add a comparison to the readme! I might even consider replacing flake8 with Ruff for linting in this project since it does a lot more than flake8 out of the box.

**Comment by dosisod** [comment]
Closing this. There is an [open issue](https://github.com/astral-sh/ruff/issues/1348) on the Ruff repo tracking which Refurb checks have been added, so anyone looking for updates on Refurb checks that are added to Ruff should look there!
