### ISSUE TITLE
[Enhancement]: Update startswith to handle not and

### ISSUE THREAD

**Issue by shaolo1** [dosisod/refurb#198]
### Overview

foo = 'abc'
bar = foo.startswith('a') or foo.startswith('b')  # warning
bar1 = not foo.startswith('a') and not foo.startswith('b') # no warning
# bar1 should be the same as bar2
bar2 = not foo.startswith(('a', 'b'))

### Proposal

startswith check should be able to handle multiple not startswith as a single not startswith via "or of ands" boolean logic.

**Comment by shaolo1** [comment]
PS.  I love what you are doing with this tool!  Thanks a million and keep up the good work!!

**Comment by dosisod** [comment]
Thank you for the kind words! And yes, this would be a good feature to add. We could also apply this to more than just `startswith`. For example, in FURB108 (`use-in-oper`), the following is not caught:

```python
foo = "abc"
bar = foo != "abc" or foo != "def"
```
Though it could be written as:
```python
bar = foo not in ("abc", "def")
```
This should be easy enough to implement, I'll see what I can do!

**Comment by dosisod** [comment]
Thank you @shaolo1 for opening this. Sorry it took so long to implement!
