### ISSUE TITLE
Allow mypy version 1.0

### ISSUE THREAD

**Issue by rhjdjong** [dosisod/refurb#199]
In our project we use both `refurb` and `mypy`. Now `mypy` has recently moved to version 1.0. However, `refurb` still requires `mypy <= 0.99`. Is it possible to allow `mypy` version 1.0 with refurb?

**Comment by dosisod** [comment]
I don't know why I didn't see this before, sorry for the late response! Refurb version 1.12.0 allows for `mypy` version 1.0, which was released a day after you opened this issue. Hopefully you've noticed this, and if not I'm sorry for the delay.
