### ISSUE TITLE
Notes with readthedocs link doesnt work

### ISSUE THREAD

**Issue by raiene** [dosisod/refurb#20]
`note: See https://refurb.readthedocs.io/en/stable/running_refurb.html#mapping-file-paths-to-modules for more info`

the page doesnt exist yet

**Comment by dosisod** [comment]
Interesting, where did you get this link? I haven't pushed anything to readthedocs, and don't have extensive documentation (most of it is in the README), so I don't think anything could have auto pushed to some place.

**Comment by raiene** [comment]
just running **refurb file.py**

`file.py:3:` error: Cannot find implementation or library stub for module named "django.db.transaction"
`file.py:3:` note: See https://refurb.readthedocs.io/en/stable/running_refurb.html#missing-imports

**Comment by dosisod** [comment]
Ah, I see what is going on. Refurb uses Mypy under the hood, so any errors containing `mypy` gets replaced with `refurb`, including links it would seem. This is a bug. The proper link is this:

https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

Sorry for the confusion! Basically Mypy cannot find any types for the `django.db.transaction` library, so it is giving an error. Installing the [django-stubs](https://github.com/typeddjango/django-stubs) package should fix this error.
