### ISSUE TITLE
[Bug]: Not respecting noqa when more than one code present

### ISSUE THREAD

**Issue by OMEGARAZER** [dosisod/refurb#217]
### Has your issue already been fixed?

- [X] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

The following code:

```python
def do_test_path_equality(result: Path, expected: str) -> bool:
    if platform.system() == "Windows":
        expected = expected.split("/")
        expected = [FileNameFormatter._format_for_windows(part) for part in expected]
        expected = Path(*expected)
    else:
        expected = Path(expected)
    return str(result).endswith(str(expected))  # noqa: FURB123,RUF100
```

Emits the following error:

```
$ refurb file.py
file.py:8:33 [FURB123]: Replace `str(x)` with `x`
```

But it should not be emitting an error instance because the line contains noqa for FURB123

### Version Info

```shell
Refurb: v1.13.0
Mypy: v1.0.0
```

### Python Version

Python 3.10.6

### Config File

```TOML
[tool.refurb]
python-version = [3.9]
```

### Extra Info

Same output from Python 3.11.2 as well.

**Comment by dosisod** [comment]
Thank you for catching this, I'll fix that right now.

An issue I would like to point out though is that the `python-version` argument in your TOML file should be `python_version`. It is not documented properly (only the `--python-version` flag is mentioned). This is made worse by the fact that unused config file fields don't cause any warnings, which means it is silently ignoring the argument. I will make a separate PR for that issue though.
