### ISSUE TITLE
[Enhancement]: Generalize FURB139: no-multiline-lstrip

### ISSUE THREAD

**Issue by theRealProHacker** [dosisod/refurb#238]
### Overview

The rule is excellent, and I have definitely already seen this one. But I have also seen it with `.strip()`, so it might be cool to generalize the rule for any strip.

I really don't know about `rstrip()`. It could also be beneficial. 

### Proposal

- [ ] Rename it to `no-multiline-strip`
- [ ] Implement the rule for `strip()` and possibly also for `rstrip()`

**Comment by dosisod** [comment]
Thank you for opening this!
