### ISSUE TITLE
[Enhancement]: documenting default of enable/disable all

### ISSUE THREAD

**Issue by jamesbraza** [dosisod/refurb#269]
### Overview

What is the default behavior for `--enable-all`/`--disable-all`?

Is `--enable-all` the default behavior?  I am trying to figure out if `enable_all = true` is a config's default, or if I should include that entry.

### Proposal

Documenting `--enable-all`'s default better in the README

**Comment by jamesbraza** [comment]
Thanks for adding `--verbose`!

I used it to determine `--enable-all` (or `enable_all = true` in config) actually is _not_ the default behavior.  Use of `--enable-all` turns on more rules (e.g. 106, 120, 137, 151, 166, etc.).

---

@dosisod one point of feedback on `--verbose` is it's currently a bit untenable, as it prints so many lines it fills my Zsh scrolling.  I could only use `--verbose` when piping `stdout` to a file.  Consider making the printout of `--verbose` be a comma separated list, not a newline separated list

**Comment by dosisod** [comment]
Good point, fixing that right now!
