### ISSUE TITLE
[Bug]: FURB173 can give false positives when non-dict objects are unpacked into a dict.

### ISSUE THREAD

**Issue by andrewmwilson** [dosisod/refurb#270]
### Has your issue already been fixed?

- [ ] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

The following code:

```python
from x import SomeClass

{"z": "z", **SomeClass()}
```

Emits the following error:

```
$ refurb file.py
file.py:3:1 [FURB173]: Replace `{..., **x1}` with `{...} | x1`
```

`SomeClass` is not a dictionary, and there are circumstances where it makes sense for `SomeClass` to support `**` keyword unpacking, but not the `|` operator.

### Version Info

```shell
1.17.0
```

### Python Version

Python 3.11.4

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Thank you for reporting this! I agree, there's an incorrect assumption that custom classes which support `**` also support `|`. This check should probably be restricted to only built-in classes, since detecting custom classes reliably might be an issue.

**Comment by andrewmwilson** [comment]
@dosisod thanks for getting back to me. I agree that it might just be better to restrict the check to built-in classes.

And thanks for all your hard work on refurb - I love it!

**Comment by owenlamont** [comment]
I get the same problem with rule FURB145 on indexable objects... refurb recommends I use a copy method which doesn't exist on the object in question.

**Comment by dosisod** [comment]
Thank you both for your feedback! I've been pretty swamped recently, just now getting around to closing some of these issues. I have yet to address the FURB145 issue, I'll save that for tomorrow.

**Comment by owenlamont** [comment]
Thanks @dosisod ! Really appreciate your effort.

**Comment by andrewmwilson** [comment]
Thanks for the fix @dosisod!
