### ISSUE TITLE
[Bug]: FURB120 advises change that would be wrong

### ISSUE THREAD

**Issue by shaolo1** [dosisod/refurb#288]
### Has your issue already been fixed?

- [X] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

The following code:

```python
def foo(bar=0, baz=1):
    print(bar, baz)

foo(0, 2)  # prints 0, 2 ...but generates warning
foo(2)  # prints 2, 1 ...generates no warning, but the result is wrong
```

Emits the following error:

```
$ refurb --enable-all refurb_default_arg.py
# refurb_default_arg.py:6:5 [FURB120]: Don't pass an argument if it is the same as the default value
```

But it should not be emitting an error instance because...
if the default value for bar is not passed and called as foo(2) then the 2 would be assigned to bar and baz would get the default of 1.  This is clearly not a great api, but as is the suggestion is wrong.

### Version Info

```shell
Refurb: v1.21.0
Mypy: v1.5.1
```

### Python Version

3.10.12

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Thank you @shaolo1 for opening this!
