### ISSUE TITLE
[Bug]: test failures with mypy 1.6.0

### ISSUE THREAD

**Issue by mr-c** [dosisod/refurb#295]
### Has your issue already been fixed?

- [X] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

Hello from Debian. Recently I uploaded a new version of mypy, `1.6.0` to Debian's development distribution. Alas, this newer version of mypy breaks refurb's `test/test_checks.py::test_checks`: https://ci.debian.net/data/autopkgtest/testing/amd64/p/python-refurb/39057922/log.gz

Any hints on how to fix this? Thanks!

### Version Info

```shell
1.12.0
```

### Python Version

3.11.6

**Comment by dosisod** [comment]
Thank you for reporting this! I should probably setup some automated testing against the `master` branch of Mypy so I can catch these sorts of bugs earlier.

**Comment by mr-c** [comment]
Thank you @dosisod!



> I should probably setup some automated testing against the `master` branch of Mypy so I can catch these sorts of bugs earlier.

Consider submitting `refurb` to https://github.com/hauntsaninja/mypy_primer, which gets run on every PR to `mypy` :-)
