### ISSUE TITLE
[Docs Request]: `python_version` when unspecified

### ISSUE THREAD

**Issue by jamesbraza** [dosisod/refurb#303]
### Overview

`python_version` shows up in the docs in a few places:
- https://github.com/dosisod/refurb/blob/v1.22.1/docs/configs/default.toml#L9
- https://github.com/dosisod/refurb/blob/v1.22.1/docs/configs/reference.toml#L25
- https://github.com/dosisod/refurb/tree/v1.22.1#setting-python-version

It would be good to document what version it will use, when unspecified.

### Proposal

It would be nice if the defaults for `python_version` would fall back on:

- Match the current interpreter's version
- `.python-version` from pyenv (like GitHub [`actions/setup-python` does](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-file-input))
- [`project.requires-python`](https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#requires-python) in `pyproject.toml`

**Comment by dosisod** [comment]
Thank you for opening this! When unspecified, Refurb uses the current interpreter version. Refurb does not look at the `.python-version` or `pyproject.toml` files for versions, though having an option to do this could be useful.

I'll update the docs to reflect the current behavior, and look into adding a flag to default to the min version in `pyproject.toml`/`.python-version` in the future.

**Comment by dosisod** [comment]
Thank you @jamesbraza for opening this!
