### ISSUE TITLE
Incorrect `len(x) > 0` suggestion

### ISSUE THREAD

**Issue by TylerYep** [dosisod/refurb#31]
This suggestion changes the resulting code:
```
x = ""
is_negative = len(x) > 0 and x[0] == "-"   # Output: False

# Violates [FURB115]: Use `x` instead of `len(x) > 0`

x = ""
is_negative = x and x[0] == "-"   # Output: ""
```

**Comment by dosisod** [comment]
Yes, this is most definitely a bug. Refurb should check to make sure that `x` is being used in a situation where a bool is expected, like an `if` block.

Thank you for reporting this!
