### ISSUE TITLE
[Bug]: False positive match for rule FURB183 when there's nested curly braces in an f string

### ISSUE THREAD

**Issue by owenlamont** [dosisod/refurb#314]
### Has your issue already been fixed?

- [ ] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

The following code:

```python
f"{timestamp:{timestamp_fmt}} ({time_since_str} ago)"
```

Emits the following error:

```
$ refurb file.py
[FURB183]: Replace `f"{timestamp_fmt}"` with `str(timestamp_fmt)`
```

But it should not be emitting an error instance because...

Refurb rule FURB183 gets a false positive when there are nested curly braces in an fstring

### Version Info

```shell
1.25.0
```

### Python Version

3.11.2

### Config File

```TOML
[tool.refurb]
ignore = [
    "FURB124", # Ignore rule to recommend chaining comparisons over anding pairs
    "FURB140", # Ignore rule to prefer starmap when iterating and constructing
    "FURB152", # Ignore rule to replace number literals that look like math constants
]
python_version = "3.9"
```

### Extra Info

None

**Comment by dosisod** [comment]
@owenlamont Thank you for reporting this!

**Comment by owenlamont** [comment]
Thanks for resolving this so fast!
