### ISSUE TITLE
[Bug]: operator.contains has reversed operator.

### ISSUE THREAD

**Issue by Skylion007** [dosisod/refurb#316]
### Has your issue already been fixed?

- [X] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug
I am upstreaming this issue from ruff (https://github.com/astral-sh/ruff/issues/9191), because I did not see any special handling for the `operator.contains` operand and the test case in this repo is also wrong.

```python
f = lambda a, b: a in b
```
should be replaced by `operator.contains` according to rule 118

[However, according to the documentation](https://docs.python.org/3/library/operator.html#operator.contains`) contains is actually equivalent to `b in a`!

This code snippet will show you that the operands are indeed reversed.
```python
import functools
import operator
f = lambda a, b: a in b
print(functools.reduce(f, ["str", {"str"}]))
print(functools.reduce(operator.contains, ["str", {"str"}]))
```

### Version Info

```shell
Technically from RUFF, but it's present on master.
```

### Python Version

3.10

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Thank you @Skylion007 for upstreaming this issue! I didn't catch this one, this is definitely a bug.

Let me know if you find any other Refurb-related issues in Ruff!
