### ISSUE TITLE
[Bug]: Suggests to replace len(text) with text in `if len(text) % 2` 

### ISSUE THREAD

**Issue by tiagocoutinho** [dosisod/refurb#318]
### Has your issue already been fixed?

- [x] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [x] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

The following code:

```python
def f(text):
    if len(text) % 2:
        return 1
    return 0
```

Emits the following suggestion:

```
$ refurb file.py
file.py:2:7 [FURB115]: Replace `len(text)` with `text`
```

but it shouldn't because the resulting code would raise TypeError

### Version Info

```shell
Refurb: v1.25.0
Mypy: v1.7.1
```

### Python Version

Python 3.10.13

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Thank you @tiagocoutinho for opening this!
