### ISSUE TITLE
[Enhancement]: extra `list` cast when calling `len`

### ISSUE THREAD

**Issue by jamesbraza** [dosisod/refurb#330]
### Overview

```python
some_dict = {"hi": 5}

# Extra
assert len(list(some_dict.keys())) == 1

# Shorter
assert len(some_dict.keys()) == 1
```

I observed an extra `list` cast around the `.keys()`. It would be cool to flag that as an extra call

### Proposal

Some new rule that can detect extra `list` conversions for calculating `len`

**Comment by dosisod** [comment]
This would be a good case to support!

This could even be shortened to `len(some_dict)` since the number of items, keys, and values are all the same:

```python
some_dict = {"hi": 5}

assert len(list(some_dict.keys())) == 1
assert len(list(some_dict.values())) == 1
assert len(list(some_dict)) == 1
assert len(some_dict.keys()) == 1
assert len(some_dict.values()) == 1
assert len(some_dict) == 1
```

**Comment by dosisod** [comment]
Thank you @jamesbraza for opening this! I've been improving Refurb's type system over the past few weeks, and better type deduction made this feature a lot easier to implement.

I'm working on a v2 release for Refurb which will include these new changes, should come out this weekend or the following weekend at the latest!

**Comment by jamesbraza** [comment]
Oh this is hype, nice and thank you! 🚀
