### ISSUE TITLE
[Bug]: false positive `FURB111` when `asyncio.get_running_loop()`

### ISSUE THREAD

**Issue by jamesbraza** [dosisod/refurb#343]
### Has your issue already been fixed?

- [X] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?
- [X] If reporting a false positive/incorrect suggestion, have you double checked that the suggested fix changes the code semantics?

### The Bug

```python
import asyncio

from pydantic import BaseModel, Field


class Foo(BaseModel):
    start_time: float = Field(
        default_factory=lambda: asyncio.get_running_loop().time()
    )
```

This code with `refurb` will want to be `Field(default_factory=asyncio.get_running_loop().time)` per `FURB111`.

The issue is that `asyncio.get_running_loop` can throw `RuntimeError: no running event loop` depending on when it's invoked.

So the bug report is that if `asyncio.get_running_loop` is part of a factory, perhaps `FURB111` should not be raised.

### Version Info

```shell
Refurb: v2.0.0
Mypy: v1.10.0
```

### Python Version

Python 3.12.3

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Thanks @jamesbraza for catching that one. We should probably disable nested function calls like `f().g()`. I'll go ahead and work on this later today!
