### ISSUE TITLE
[Enhancement]: opinions on `isinstance` with `tuple` or union (`|`)?

### ISSUE THREAD

**Issue by jamesbraza** [dosisod/refurb#345]
### Overview

It turns out with Python 3.10+ that `isinstance` ([docs](https://docs.python.org/3/library/functions.html#isinstance)) supports union syntax:

```python
isinstance(5, (int, str))
isinstance(5, int | str)  # New in Python 3.10
```

### Proposal

Actually I think union syntax is pretty slick, and easier to read. I think it would be a cool `refurb` rule to suggest this refactor.

What do you think?

**Comment by dosisod** [comment]
I think this is a good feature, but it is already implemented in [Pyupgrade](https://github.com/asottile/pyupgrade) and [Ruff](https://docs.astral.sh/ruff/rules/non-pep604-isinstance/), so I am hesitent to re-implement it for the sake of having it in Refurb as well.

In general, my stance has been that if a given check/rule already exists in another tool like Ruff, flake8, etc, there isn't much use in re-implementing it.

Thank you for opening this though, and sorry for the delayed response.
