### ISSUE TITLE
Question: Why do you require python >=3.10?

### ISSUE THREAD

**Issue by dmilcevski** [dosisod/refurb#42]
I was wondering why do you require python 3.10 as min version? Thank you!

**Comment by dosisod** [comment]
Great question! Python 3.10 introduced [Structural Pattern Matching](https://peps.python.org/pep-0636/#appendix-a-quick-intro) which is used heavily in this codebase. I have been looking into [mypyc](https://github.com/python/mypy/tree/master/mypyc#readme), which should improve the speed of Refurb, and could also allow for running in older versions of Python.

As it stands currently, Refurb will be sticking with Python 3.10. It can check code from earlier versions of Python, but the tool itself must be ran under 3.10. It would be really cool to transpile Refurb for older versions of Python, but I doubt it will work. I would love to be proven wrong though!

**Comment by henryiii** [comment]
I've done the same thing elsewhere, for the same reason. I'd generally assume checks are being run by developers and developers should be able to upgrade Python more easily than users. :)

**Comment by dmilcevski** [comment]
Thanks for your fast response. Our repos allow >=3.7<=3.10, but I woudn't restrict to >=3.10. However, the pre-commit hook is really useful, so for now this is a nice solution.
Thanks!

**Comment by dosisod** [comment]
Closing this in favor of #57. If compatibility with earlier versions of Python is made available with the mypyc migration, I will make sure to mention it here.

Thank you for initially reporting this @dmilcevski!
