### ISSUE TITLE
FURB107 and multiple exceptions

### ISSUE THREAD

**Issue by henryiii** [dosisod/refurb#45]
The suggestion for multiple exceptions is slightly wrong:

```
skbuild/cmaker.py:417:13 [FURB107]: Use `with suppress((AttributeError, KeyError)): ...` instead of `try: ... except (AttributeError, KeyError): pass`
```

It should be `with suppress(AttributeError, KeyError): ...`

I'm enjoying running `pipx run refurb src` on several projects. :)

**Comment by dosisod** [comment]
I'm glad you are enjoying Refurb! And thank you for reporting this, I am fixing it now.
