### ISSUE TITLE
Reported error is not correct

### ISSUE THREAD

**Issue by JacekPliszka** [dosisod/refurb#46]
```
if a == 1 or a == b and a > 3:
    print(1)
```
generates hint:
> t.py:1:4 [FURB108]: Use `x in (y, z)` instead of `x == y or x == z`

Which is not correct due to presence of and which has higher precedence

**Comment by dosisod** [comment]
Thank you for reporting this!

**Comment by henryiii** [comment]
This happens if there are parenthesis there too, I notice this in one of my runs.
