### ISSUE TITLE
Question: Source of useful rules/heuristics for adding checks

### ISSUE THREAD

**Issue by bbkgh** [dosisod/refurb#56]
Hi. I want to write and contribute some checks into this repository but i haven't any check/rule at this moment. Is there any written source of this rules? Anyone can introduce some rules/blog posts/existing tools, ... here. I think an aggregation of possible future checks descriptions (e.g as a file in this repo) can increase speed of enriching this useful tool.

**Comment by dosisod** [comment]
Thank you for bringing this up! I think that a long-running list of checks to add is a great idea. As for documentation for how to write checks, they exist somewhat (see [the README](https://github.com/dosisod/refurb#writing-your-own-check)), but I think we can do better.

I will whip up some documentation over the weekend detailing how to write new checks.
