### ISSUE TITLE
FURB111 on lambda unpacking dict

### ISSUE THREAD

**Issue by igordertigor** [dosisod/refurb#64]
Checking the following code with `refurb` gives me a `FURB111` error and suggests that I drop the lambda:
```python
def f(x, y):
    print(f'{x = }, {y = }')


def g(func):
    func({'x': 1, 'y': 2})


if __name__ == '__main__':
    g(lambda d: f(**d))
```

However, if the last line is changed to `g(f)`, then the code fails, because the dictionary has not been unpacked.

**Comment by dosisod** [comment]
Thank you for reporting this, I go ahead and fix that later today!

**Comment by dosisod** [comment]
Thanks! It was a pretty easy fix
