### ISSUE TITLE
Please provide a help text

### ISSUE THREAD

**Issue by kseistrup** [dosisod/refurb#9]
This is uphill:

```sh
$ refurb
refurb: no arguments passed
$ refurb -h      # Let's try the traditional short help switch
refurb: unsupported option "-h"
$ refurb --help  # Long options, then?
refurb: unsupported option "--help"
$ refurb -help   # Go-language style?
refurb: unsupported option "-help"
$ refurb help    # Or perhaps as a command?
refurb: can't read file 'help': No such file or directory
$ # Giving up…
```

The README mentions `--explain`, `--ignore`, `--load`, and `--debug`, but it would be really useful to have `-h`/`--help`.

I'm not even sure which version I am reporting for, since `-V`/`--version` is missing, too.

Please.

**Comment by dosisod** [comment]
Thank you for reporting this! This is a pretty important thing to forget, I will add both of these in today
