### ISSUE TITLE
[Bug]: FURB110 not emitted for conditions splitted on multiple lines

### ISSUE THREAD

**Issue by eric-bonfadini** [dosisod/refurb#97]
### The Bug

The following simplified code:

```python
from dataclasses import dataclass

@dataclass()
class Person:
    name: str
    surname: str    


person = Person(name="John", surname="Doe")

print(person.name if person.name else "N/A")
print(
    person.surname
    if person.surname
    else "N/A"
)
```

Emits the following error:

```
$ refurb file.py
file.py:12:7 [FURB110]: Use `x or y` instead of `x if x else y`
```

But it should be emitting the same error also for line 14

### Version Info

```shell
Refurb: v1.5.0
Mypy: v0.982
```

### Python Version

Python 3.10.8

### Config File

```TOML
# N/A
```

### Extra Info

None

**Comment by dosisod** [comment]
Thank you for reporting this! Currently nodes are considered "the same" if their string representations are the same. This is flawed for a number of reasons, the main one being that different line numbers create different string representations.

For example, when using the `--debug` flag (output truncated):

```
ConditionalExpr:11(
  Condition(
    MemberExpr:11(
      NameExpr(person [x.person])
      name))
  MemberExpr:11(
    NameExpr(person [x.person])
    name)
  StrExpr(N/A))
ConditionalExpr:13(
  Condition(
    MemberExpr:14(
      NameExpr(person [x.person])
      surname))
  MemberExpr:13(
    NameExpr(person [x.person])
    surname)
  StrExpr(N/A))
```

You can see the nodes on line 11 match up, but the nodes on lines 13/14 do not.

Hopefully this gives some more insight as to why this is an issue. I expect this will be an easy fix!
