### ISSUE TITLE
Consider adding issue templates for enhancements?

### ISSUE THREAD

**Issue by The-Compiler** [dosisod/refurb#99]
With #67, opening a new issue shows:

![image](https://user-images.githubusercontent.com/625793/200569311-235b4da7-cfa0-4180-b768-891fa6afdc5a.png)

while there is a small "Open a blank issue" link at the bottom, this seems to imply that using issues for things other than bugs (e.g. feature requests) is discouraged - which I think isn't the case, looking at other open issues. Perhaps there should be another such template (could mostly be blank, I suppose) for enhancement issues?

**Comment by dosisod** [comment]
Thank you for reporting this! Yes, I think having a template for feature requests is a good idea. I will go ahead and make one sometime this week.
